<pre class='metadata'>
Title: Requirements for the Network of Terms
Shortname: nde-requirements-network-of-terms
Status: LS
Markup Shorthands: css yes, markdown yes
URL: https://netwerk-digitaal-erfgoed.github.io/requirements-network-of-terms/
Editor: Sjors de Valk, Dutch Digital Heritage Network https://www.netwerkdigitaalerfgoed.nl/en, sjors@sjorsdevalk.nl
Abstract: This document describes the requirements that the Network of Terms must meet in order to be used in the Dutch Digital Heritage Network (NDE).
</pre>
